services:
  api-server:
    build:
      context: .
    container_name: api-server-temperature
    ports:
      - "8080:8080"
    environment:
      - WEATHER_API_KEY=your_api_key_here
  
  api-server-tests:
    build:
      context: .
      target: test
    environment:
      - WEATHER_API_KEY=your_api_key_here